FROM skygeario/skygear-nodedev

USER root

ENV NODE_PATH /usr/local/lib/node_modules

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN \
  cd /usr/src/app && \
  npm install && \
  npm run prepublish && \
  npm link

ENTRYPOINT ["/usr/local/bin/tini", "--"]
CMD ["skygear-node"]
