version: '2'

services:
  db:
    image: mdillon/postgis:9.5
    volumes:
    - db_data:/var/lib/postgresql/data

  app:
    image: quay.io/skygeario/skygear-server:canary
    ports:
    - "3000:3000"
    volumes:
    - app_data:/go/src/app/data
    links:
    - db
    command: skygear-server --http
    environment:
      # `db` in the following string should match the name of the database
      # container above.
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      TOKEN_STORE: jwt
      TOKEN_STORE_SECRET: my_skygear_jwt_secret
      # GOMAXPROCS - The maximum number of Go threads for execution.
      # When unspecified, the default is the number of CPU available, which
      # is the recommended setting.
      #GOMAXPROCS: 1
      PLUGINS: NODE
      NODE_TRANSPORT: http
      NODE_PATH: http://plugin:9000

  plugin:
    image: quay.io/skygeario/skygear-node:canary
    volumes:
    - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      PUBSUB_URL: PUBSUB_URL=ws://app:3000/pubsub
      SKYGEAR_ENDPOINT: http://app:3000
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
